#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ouimeaux
Version  : 0.8
Release  : 7
URL      : https://files.pythonhosted.org/packages/a3/3a/7b3677d29896282314e492d123a1e72fa29f263be4892188aa7d54aa769f/ouimeaux-0.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/a3/3a/7b3677d29896282314e492d123a1e72fa29f263be4892188aa7d54aa769f/ouimeaux-0.8.tar.gz
Summary  : Open source control for Belkin WeMo devices
Group    : Development/Tools
License  : BSD-3-Clause Python-2.0
Requires: ouimeaux-bin = %{version}-%{release}
Requires: ouimeaux-license = %{version}-%{release}
Requires: ouimeaux-python = %{version}-%{release}
Requires: ouimeaux-python3 = %{version}-%{release}
Requires: PyYAML
Requires: gevent
Requires: python-future
Requires: requests
Requires: six
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : gevent
BuildRequires : python-future
BuildRequires : requests
BuildRequires : six

%description
==============================
ouimeaux
==============================

.. image:: https://badge.fury.io/py/ouimeaux.png
    :target: http://badge.fury.io/py/ouimeaux
    
.. image:: https://travis-ci.org/iancmcc/ouimeaux.png?branch=develop
        :target: https://travis-ci.org/iancmcc/ouimeaux

.. image:: https://pypip.in/d/ouimeaux/badge.png
        :target: https://crate.io/packages/ouimeaux?version=latest


Open source control for Belkin WeMo devices

* Free software: BSD license
* Documentation: http://ouimeaux.rtfd.org.

Features
--------

* Supports WeMo Switch, Light Switch, Insight Switch and Motion
* Command-line tool to discover and control devices in your environment
* REST API to obtain information and perform actions on devices
* Simple responsive Web app provides device control on mobile
* Python API to interact with device at a low level




History
-------

Release 0.8.0 (July 30, 2016)
+++++++++++++++++++++++++++++
- Randomize subscription ports to enable simultaneous ouimeaux scripts (thanks @bennytheshap)
- Fix for WeMo LED Light support (thanks @sstangle73)
- #32: Removed address cache, broke server out into optional feature
- Fix for Maker state reporting (thanks @pavoni)
- Filter by SSDP location, fixing case where multiple devices respond from the same IP (thanks @szakharchenko)
- Fix Maker event handlers, which were being passed as bridges (thanks @maxlazarov)
- Work around gevent-socketio bug by explicitly casting header value as string
- Fix for inconsistent Light state (thanks @canduuk)
- StateChange signals are now a separate class and do not fire if value is unchanged (thanks @esecules)
- Python 3 support (thanks to @drock371)

Release 0.7.9 (March 17, 2015)
++++++++++++++++++++++++++++++
- Command line support for WeMo LED Light (thanks @fritz-fritz)
- Command line support for WeMo Maker (thanks @logjames)
- Support for 2.0.0 firmware (thanks @fritz-fritz)
- Bug fixes

Release 0.7.3 (August 10, 2014)
++++++++++++++++++++++++++++++++
- Fixed #18: Error when run as root
- Fixed #26: Evict devices from cache when unreachable
- Fixed #29: GetPower stopped working for Insight devices
- Fixed #31: Add blink method on switches, include in REST API
- Fixed #33, #37: Handle invalid devices without dying
- Fixed #35: Require requests >= 2.3.0
- Fixed #40: Retry requests in the event of failure
- Fixed #47: Don't choke on invalid newlines in XML returned by switches
             (thanks to @fingon)

Release 0.7.2 (January 28, 2014)
++++++++++++++++++++++++++++++++
- Fix a bug with using query parameters on /api/device

Release 0.7 (January 27, 2014)
++++++++++++++++++++++++++++++
- Added REST API
- Added Web app

Release 0.6 (January 25, 2014)
++++++++++++++++++++++++++++++++
- Added signals framework
- Fixed #16, #19, #22: Defensively resubscribe to events when device responds with an error
- Fixed #15: Signals framework includes relevant device when sending signal
- Refactored structure, added Sphinx docs

Release 0.5.3 (January 25, 2014)
++++++++++++++++++++++++++++++++
- Fixed #20: Allow timeout in environment.wait()
- Fixed #21: Add Insight support

Release 0.5.2 (November 23, 2013)
+++++++++++++++++++++++++++++++++
- Fixed #14: Indicate Connection:close header to avoid logging when WeMo sends
  invalid HTTP response.

Release 0.5.1 (November 9, 2013)
++++++++++++++++++++++++++++++++
- Fixed #10: Updated subscriber listener to use more reliable method of
  retrieving non-loopback IP address; updated docs to fix typo in listener
  registration example (thanks to @benhoyle, @francxk)
- Fixed #11: Remove instancemethod objects before attempting to pickle devices
  in the cache (thanks @piperde, @JonPenner, @tomtomau, @masilu77)

Release 0.5 (October 14, 2013)
+++++++++++++++++++++++++++++++
- Added fuzzy matching of device name when searching/toggling from command line
- Added ``status`` mode to print status for all devices
- Added ``switch status`` mode to print status for specific device
- Added flags for all command-line options
- Fixed #9: Removed unused fcntl import that precluded Windows usage (thanks to
  @deepseven)

Release 0.4.3 (August 31, 2013)
+++++++++++++++++++++++++++++++
- Used new method of obtaining local IP for discovery that is less likely to
  return loopback
- Exit with failure and instructions for solution if loopback IP is used
- Updated installation docs to include python-dev and pip instructions (patch
  by @fnaard)
- Fixed README inclusion bug that occasionally broke installation via pip.
- Added ``--debug`` option to enable debug logging to stdout

Release 0.4 (August 17, 2013)
+++++++++++++++++++++++++++++
- Fixed #7: Added support for light switch devices (patch by nschrenk).
- Fixed #6: Added "wemo clear" command to clear the device cache.

Release 0.3 (May 25, 2013)
++++++++++++++++++++++++++
- Fixed #4: Added ability to specify ip:port for discovery server binding. Removed
  documentation describing need to disable SSDP service on Windows.
- Fixed #5: Added device cache for faster results.
- Added configuration file.
- Added ability to configure aliases for devices to avoid quoting strings on
  the command line.
- Added 'toggle' command to command line switch control.

Release 0.2 (April 21, 2013)
++++++++++++++++++++++++++++++
- Fixed #1: Added ability to subscribe to motion and switch state change events.
- Added Windows installation details to README (patch by @brianpeiris)
- Cleaned up UDP server lifecycle so rediscovery doesn't try to start it back up.

Release 0.1 (February 2, 2013)
++++++++++++++++++++++++++++++
- Initial release.

* First release on PyPI.

%package bin
Summary: bin components for the ouimeaux package.
Group: Binaries
Requires: ouimeaux-license = %{version}-%{release}

%description bin
bin components for the ouimeaux package.


%package license
Summary: license components for the ouimeaux package.
Group: Default

%description license
license components for the ouimeaux package.


%package python
Summary: python components for the ouimeaux package.
Group: Default
Requires: ouimeaux-python3 = %{version}-%{release}

%description python
python components for the ouimeaux package.


%package python3
Summary: python3 components for the ouimeaux package.
Group: Default
Requires: python3-core
Provides: pypi(ouimeaux)

%description python3
python3 components for the ouimeaux package.


%prep
%setup -q -n ouimeaux-0.8
cd %{_builddir}/ouimeaux-0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583196117
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ouimeaux
cp %{_builddir}/ouimeaux-0.8/LICENSE %{buildroot}/usr/share/package-licenses/ouimeaux/bd94797889ab4f12d1037fa66c10dca1d6ab6cc3
cp %{_builddir}/ouimeaux-0.8/ouimeaux/pysignals/LICENSE.txt %{buildroot}/usr/share/package-licenses/ouimeaux/6b592f04d077053c80d47f3a8321d21aad45dd69
cp %{_builddir}/ouimeaux-0.8/ouimeaux/pysignals/license.python.txt %{buildroot}/usr/share/package-licenses/ouimeaux/e6e9a006706b5c1187a7ce23ca2135406cc0388d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wemo

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ouimeaux/6b592f04d077053c80d47f3a8321d21aad45dd69
/usr/share/package-licenses/ouimeaux/bd94797889ab4f12d1037fa66c10dca1d6ab6cc3
/usr/share/package-licenses/ouimeaux/e6e9a006706b5c1187a7ce23ca2135406cc0388d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
